export const REPO_SINCE = 'REPO_SINCE';
export const REPO_LANGUAGE = 'REPO_LANGUAGE';
export const REPO_SPOKEN_LANGUAGE = 'REPO_SPOKEN_LANGUAGE';

export const sinces = [
  '今日',
  '这周',
  '这个月',
];

export const sincesMap: {[key: string]: string} = {
  '今日': 'daily',
  '这周': 'weekly',
  '这个月': 'monthly',
};

export const spokenLanguages = [
  '不限语言',
  '中文',
  '英文',
];

export const spokenLanguagesMap: {[key: string]: string} = {
  '不限语言': '',
  '中文': 'zh',
  '英文': 'en',
};

export const languages = [
  "不限语言",
  "C",
  "C++",
  "Java",
  "JavaScript",
  "Kotlin",
  "Python",
  "TypeScript",
  "Unknown languages",
  "1C Enterprise",
  "4D",
  "ABAP",
  "ABNF",
  "ActionScript",
  "Ada",
  "Adobe Font Metrics",
  "Agda",
  "AGS Script",
  "Alloy",
  "Alpine Abuild",
  "Altium Designer",
  "AMPL",
  "AngelScript",
  "Ant Build System",
  "ANTLR",
  "ApacheConf",
  "Apex",
  "API Blueprint",
  "APL",
  "Apollo Guidance Computer",
  "AppleScript",
  "Arc",
  "AsciiDoc",
  "ASN.1",
  "ASP",
  "AspectJ",
  "Assembly",
  "Asymptote",
  "ATS",
  "Augeas",
  "AutoHotkey",
  "AutoIt",
  "Awk",
  "Ballerina",
  "Batchfile",
  "Befunge",
  "BibTeX",
  "Bison",
  "BitBake",
  "Blade",
  "BlitzBasic",
  "BlitzMax",
  "Bluespec",
  "Boo",
  "Brainfuck",
  "Brightscript",
  "Zeek",
  "C",
  "C#",
  "C++",
  "C-ObjDump",
  "C2hs Haskell",
  "Cabal Config",
  "Cap'n Proto",
  "CartoCSS",
  "Ceylon",
  "Chapel",
  "Charity",
  "ChucK",
  "Cirru",
  "Clarion",
  "Clean",
  "Click",
  "CLIPS",
  "Clojure",
  "Closure Templates",
  "Cloud Firestore Security Rules",
  "CMake",
  "COBOL",
  "CodeQL",
  "CoffeeScript",
  "ColdFusion",
  "ColdFusion CFC",
  "COLLADA",
  "Common Lisp",
  "Common Workflow Language",
  "Component Pascal",
  "CoNLL-U",
  "Cool",
  "Coq",
  "Cpp-ObjDump",
  "Creole",
  "Crystal",
  "CSON",
  "Csound",
  "Csound Document",
  "Csound Score",
  "CSS",
  "CSV",
  "Cuda",
  "cURL Config",
  "CWeb",
  "Cycript",
  "Cython",
  "D",
  "D-ObjDump",
  "Dafny",
  "Darcs Patch",
  "Dart",
  "DataWeave",
  "desktop",
  "Dhall",
  "Diff",
  "DIGITAL Command Language",
  "dircolors",
  "DirectX 3D File",
  "DM",
  "DNS Zone",
  "Dockerfile",
  "Dogescript",
  "DTrace",
  "Dylan",
  "E",
  "Eagle",
  "Easybuild",
  "EBNF",
  "eC",
  "Ecere Projects",
  "ECL",
  "ECLiPSe",
  "EditorConfig",
  "Edje Data Collection",
  "edn",
  "Eiffel",
  "EJS",
  "Elixir",
  "Elm",
  "Emacs Lisp",
  "EmberScript",
  "EML",
  "EQ",
  "Erlang",
  "F#",
  "F*",
  "Factor",
  "Fancy",
  "Fantom",
  "Faust",
  "FIGlet Font",
  "Filebench WML",
  "Filterscript",
  "fish",
  "FLUX",
  "Formatted",
  "Forth",
  "Fortran",
  "Fortran Free Form",
  "FreeMarker",
  "Frege",
  "Futhark",
  "G-code",
  "Game Maker Language",
  "GAML",
  "GAMS",
  "GAP",
  "GCC Machine Description",
  "GDB",
  "GDScript",
  "Genie",
  "Genshi",
  "Gentoo Ebuild",
  "Gentoo Eclass",
  "Gerber Image",
  "Gettext Catalog",
  "Gherkin",
  "Git Attributes",
  "Git Config",
  "GLSL",
  "Glyph",
  "Glyph Bitmap Distribution Format",
  "GN",
  "Gnuplot",
  "Go",
  "Golo",
  "Gosu",
  "Grace",
  "Gradle",
  "Grammatical Framework",
  "Graph Modeling Language",
  "GraphQL",
  "Graphviz (DOT)",
  "Groovy",
  "Groovy Server Pages",
  "Hack",
  "Haml",
  "Handlebars",
  "HAProxy",
  "Harbour",
  "Haskell",
  "Haxe",
  "HCL",
  "HiveQL",
  "HLSL",
  "HolyC",
  "HTML",
  "HTML+Django",
  "HTML+ECR",
  "HTML+EEX",
  "HTML+ERB",
  "HTML+PHP",
  "HTML+Razor",
  "HTTP",
  "HXML",
  "Hy",
  "HyPhy",
  "IDL",
  "Idris",
  "Ignore List",
  "IGOR Pro",
  "Inform 7",
  "INI",
  "Inno Setup",
  "Io",
  "Ioke",
  "IRC log",
  "Isabelle",
  "Isabelle ROOT",
  "J",
  "Jasmin",
  "Java",
  "Java Properties",
  "Java Server Pages",
  "JavaScript",
  "JavaScript+ERB",
  "JFlex",
  "Jison",
  "Jison Lex",
  "Jolie",
  "JSON",
  "JSON with Comments",
  "JSON5",
  "JSONiq",
  "JSONLD",
  "Jsonnet",
  "JSX",
  "Julia",
  "Jupyter Notebook",
  "KiCad Layout",
  "KiCad Legacy Layout",
  "KiCad Schematic",
  "Kit",
  "Kotlin",
  "KRL",
  "LabVIEW",
  "Lasso",
  "Latte",
  "Lean",
  "Less",
  "Lex",
  "LFE",
  "LilyPond",
  "Limbo",
  "Linker Script",
  "Linux Kernel Module",
  "Liquid",
  "Literate Agda",
  "Literate CoffeeScript",
  "Literate Haskell",
  "LiveScript",
  "LLVM",
  "Logos",
  "Logtalk",
  "LOLCODE",
  "LookML",
  "LoomScript",
  "LSL",
  "LTspice Symbol",
  "Lua",
  "M",
  "M4",
  "M4Sugar",
  "Macaulay2",
  "Makefile",
  "Mako",
  "Markdown",
  "Marko",
  "Mask",
  "Mathematica",
  "MATLAB",
  "Maven POM",
  "Max",
  "MAXScript",
  "mcfunction",
  "MediaWiki",
  "Mercury",
  "Meson",
  "Metal",
  "Microsoft Developer Studio Project",
  "MiniD",
  "Mirah",
  "mIRC Script",
  "MLIR",
  "Modelica",
  "Modula-2",
  "Modula-3",
  "Module Management System",
  "Monkey",
  "Moocode",
  "MoonScript",
  "Motorola 68K Assembly",
  "MQL4",
  "MQL5",
  "MTML",
  "MUF",
  "mupad",
  "Muse",
  "Myghty",
  "nanorc",
  "NASL",
  "NCL",
  "Nearley",
  "Nemerle",
  "nesC",
  "NetLinx",
  "NetLinx+ERB",
  "NetLogo",
  "NewLisp",
  "Nextflow",
  "Nginx",
  "Nim",
  "Ninja",
  "Nit",
  "Nix",
  "NL",
  "NPM Config",
  "NSIS",
  "Nu",
  "NumPy",
  "ObjDump",
  "Object Data Instance Notation",
  "Objective-C",
  "Objective-C++",
  "Objective-J",
  "ObjectScript",
  "OCaml",
  "Odin",
  "Omgrofl",
  "ooc",
  "Opa",
  "Opal",
  "Open Policy Agent",
  "OpenCL",
  "OpenEdge ABL",
  "OpenQASM",
  "OpenRC runscript",
  "OpenSCAD",
  "OpenStep Property List",
  "OpenType Feature File",
  "Org",
  "Ox",
  "Oxygene",
  "Oz",
  "P4",
  "Pan",
  "Papyrus",
  "Parrot",
  "Parrot Assembly",
  "Parrot Internal Representation",
  "Pascal",
  "Pawn",
  "Pep8",
  "Perl",
  "PHP",
  "Pic",
  "Pickle",
  "PicoLisp",
  "PigLatin",
  "Pike",
  "PlantUML",
  "PLpgSQL",
  "PLSQL",
  "Pod",
  "Pod 6",
  "PogoScript",
  "Pony",
  "PostCSS",
  "PostScript",
  "POV-Ray SDL",
  "PowerBuilder",
  "PowerShell",
  "Prisma",
  "Processing",
  "Proguard",
  "Prolog",
  "Propeller Spin",
  "Protocol Buffer",
  "Public Key",
  "Pug",
  "Puppet",
  "Pure Data",
  "PureBasic",
  "PureScript",
  "Python",
  "Python console",
  "Python traceback",
  "q",
  "QMake",
  "QML",
  "Quake",
  "R",
  "Racket",
  "Ragel",
  "Raku",
  "RAML",
  "Rascal",
  "Raw token data",
  "RDoc",
  "Readline Config",
  "REALbasic",
  "Reason",
  "Rebol",
  "Red",
  "Redcode",
  "Regular Expression",
  "Ren'Py",
  "RenderScript",
  "reStructuredText",
  "REXX",
  "RHTML",
  "Rich Text Format",
  "Ring",
  "Riot",
  "RMarkdown",
  "RobotFramework",
  "Roff",
  "Roff Manpage",
  "Rouge",
  "RPC",
  "RPM Spec",
  "Ruby",
  "RUNOFF",
  "Rust",
  "Sage",
  "SaltStack",
  "SAS",
  "Sass",
  "Scala",
  "Scaml",
  "Scheme",
  "Scilab",
  "SCSS",
  "sed",
  "Self",
  "ShaderLab",
  "Shell",
  "ShellSession",
  "Shen",
  "Sieve",
  "Slash",
  "Slice",
  "Slim",
  "Smali",
  "Smalltalk",
  "Smarty",
  "SmPL",
  "SMT",
  "Solidity",
  "SourcePawn",
  "SPARQL",
  "Spline Font Database",
  "SQF",
  "SQL",
  "SQLPL",
  "Squirrel",
  "SRecode Template",
  "SSH Config",
  "Stan",
  "Standard ML",
  "Starlark",
  "Stata",
  "STON",
  "Stylus",
  "SubRip Text",
  "SugarSS",
  "SuperCollider",
  "Svelte",
  "SVG",
  "Swift",
  "SWIG",
  "SystemVerilog",
  "Tcl",
  "Tcsh",
  "Tea",
  "Terra",
  "TeX",
  "Texinfo",
  "Text",
  "Textile",
  "Thrift",
  "TI Program",
  "TLA",
  "TOML",
  "TSQL",
  "TSX",
  "Turing",
  "Turtle",
  "Twig",
  "TXL",
  "Type Language",
  "TypeScript",
  "Unified Parallel C",
  "Unity3D Asset",
  "Unix Assembly",
  "Uno",
  "UnrealScript",
  "UrWeb",
  "V",
  "Vala",
  "VBA",
  "VBScript",
  "VCL",
  "Verilog",
  "VHDL",
  "Vim script",
  "Vim Snippet",
  "Visual Basic .NET",
  "Visual Basic .NET",
  "Volt",
  "Vue",
  "Wavefront Material",
  "Wavefront Object",
  "wdl",
  "Web Ontology Language",
  "WebAssembly",
  "WebIDL",
  "WebVTT",
  "Wget Config",
  "Windows Registry Entries",
  "wisp",
  "Wollok",
  "World of Warcraft Addon Data",
  "X BitMap",
  "X Font Directory Index",
  "X PixMap",
  "X10",
  "xBase",
  "XC",
  "XCompose",
  "XML",
  "XML Property List",
  "Xojo",
  "XPages",
  "XProc",
  "XQuery",
  "XS",
  "XSLT",
  "Xtend",
  "Yacc",
  "YAML",
  "YANG",
  "YARA",
  "YASnippet",
  "ZAP",
  "Zeek",
  "ZenScript",
  "Zephir",
  "Zig",
  "ZIL",
  "Zimpl"
];

export const languagesMap: {[key: string]: string} = {
  "不限语言": "",
  "C": "c",
  "C++": "c%2B+",
  "Java": "java",
  "JavaScript": "javascript",
  "Kotlin": "kotlin",
  "Python": "python",
  "TypeScript": "typescript",
  "Unknown languages": "unknown-languages",
  "1C Enterprise": "1c-enterprise",
  "4D": "4d",
  "ABAP": "abap",
  "ABNF": "abnf",
  "ActionScript": "actionscript",
  "Ada": "ada",
  "Adobe Font Metrics": "adobe-font metrics",
  "Agda": "agda",
  "AGS Script": "ags-script",
  "Alloy": "alloy",
  "Alpine Abuild": "alpine-abuild",
  "Altium Designer": "altium-designer",
  "AMPL": "ampl",
  "AngelScript": "angelscript",
  "Ant Build System": "ant-build system",
  "ANTLR": "antlr",
  "ApacheConf": "apacheconf",
  "Apex": "apex",
  "API Blueprint": "api-blueprint",
  "APL": "apl",
  "Apollo Guidance Computer": "apollo-guidance computer",
  "AppleScript": "applescript",
  "Arc": "arc",
  "AsciiDoc": "asciidoc",
  "ASN.1": "asn.1",
  "ASP": "asp",
  "AspectJ": "aspectj",
  "Assembly": "assembly",
  "Asymptote": "asymptote",
  "ATS": "ats",
  "Augeas": "augeas",
  "AutoHotkey": "autohotkey",
  "AutoIt": "autoit",
  "Awk": "awk",
  "Ballerina": "ballerina",
  "Batchfile": "batchfile",
  "Befunge": "befunge",
  "BibTeX": "bibtex",
  "Bison": "bison",
  "BitBake": "bitbake",
  "Blade": "blade",
  "BlitzBasic": "blitzbasic",
  "BlitzMax": "blitzmax",
  "Bluespec": "bluespec",
  "Boo": "boo",
  "Brainfuck": "brainfuck",
  "Brightscript": "brightscript",
  "Zeek": "zeek",
  "C#": "c%23",
  "C-ObjDump": "c-objdump",
  "C2hs Haskell": "c2hs-haskell",
  "Cabal Config": "cabal-config",
  "Cap'n Proto": "cap'n-proto",
  "CartoCSS": "cartocss",
  "Ceylon": "ceylon",
  "Chapel": "chapel",
  "Charity": "charity",
  "ChucK": "chuck",
  "Cirru": "cirru",
  "Clarion": "clarion",
  "Clean": "clean",
  "Click": "click",
  "CLIPS": "clips",
  "Clojure": "clojure",
  "Closure Templates": "closure-templates",
  "Cloud Firestore Security Rules": "cloud-firestore security rules",
  "CMake": "cmake",
  "COBOL": "cobol",
  "CodeQL": "codeql",
  "CoffeeScript": "coffeescript",
  "ColdFusion": "coldfusion",
  "ColdFusion CFC": "coldfusion-cfc",
  "COLLADA": "collada",
  "Common Lisp": "common-lisp",
  "Common Workflow Language": "common-workflow language",
  "Component Pascal": "component-pascal",
  "CoNLL-U": "conll-u",
  "Cool": "cool",
  "Coq": "coq",
  "Cpp-ObjDump": "cpp-objdump",
  "Creole": "creole",
  "Crystal": "crystal",
  "CSON": "cson",
  "Csound": "csound",
  "Csound Document": "csound-document",
  "Csound Score": "csound-score",
  "CSS": "css",
  "CSV": "csv",
  "Cuda": "cuda",
  "cURL Config": "curl-config",
  "CWeb": "cweb",
  "Cycript": "cycript",
  "Cython": "cython",
  "D": "d",
  "D-ObjDump": "d-objdump",
  "Dafny": "dafny",
  "Darcs Patch": "darcs-patch",
  "Dart": "dart",
  "DataWeave": "dataweave",
  "desktop": "desktop",
  "Dhall": "dhall",
  "Diff": "diff",
  "DIGITAL Command Language": "digital-command language",
  "dircolors": "dircolors",
  "DirectX 3D File": "directx-3d file",
  "DM": "dm",
  "DNS Zone": "dns-zone",
  "Dockerfile": "dockerfile",
  "Dogescript": "dogescript",
  "DTrace": "dtrace",
  "Dylan": "dylan",
  "E": "e",
  "Eagle": "eagle",
  "Easybuild": "easybuild",
  "EBNF": "ebnf",
  "eC": "ec",
  "Ecere Projects": "ecere-projects",
  "ECL": "ecl",
  "ECLiPSe": "eclipse",
  "EditorConfig": "editorconfig",
  "Edje Data Collection": "edje-data collection",
  "edn": "edn",
  "Eiffel": "eiffel",
  "EJS": "ejs",
  "Elixir": "elixir",
  "Elm": "elm",
  "Emacs Lisp": "emacs-lisp",
  "EmberScript": "emberscript",
  "EML": "eml",
  "EQ": "eq",
  "Erlang": "erlang",
  "F#": "f%23",
  "F*": "f*",
  "Factor": "factor",
  "Fancy": "fancy",
  "Fantom": "fantom",
  "Faust": "faust",
  "FIGlet Font": "figlet-font",
  "Filebench WML": "filebench-wml",
  "Filterscript": "filterscript",
  "fish": "fish",
  "FLUX": "flux",
  "Formatted": "formatted",
  "Forth": "forth",
  "Fortran": "fortran",
  "Fortran Free Form": "fortran-free form",
  "FreeMarker": "freemarker",
  "Frege": "frege",
  "Futhark": "futhark",
  "G-code": "g-code",
  "Game Maker Language": "game-maker language",
  "GAML": "gaml",
  "GAMS": "gams",
  "GAP": "gap",
  "GCC Machine Description": "gcc-machine description",
  "GDB": "gdb",
  "GDScript": "gdscript",
  "Genie": "genie",
  "Genshi": "genshi",
  "Gentoo Ebuild": "gentoo-ebuild",
  "Gentoo Eclass": "gentoo-eclass",
  "Gerber Image": "gerber-image",
  "Gettext Catalog": "gettext-catalog",
  "Gherkin": "gherkin",
  "Git Attributes": "git-attributes",
  "Git Config": "git-config",
  "GLSL": "glsl",
  "Glyph": "glyph",
  "Glyph Bitmap Distribution Format": "glyph-bitmap distribution format",
  "GN": "gn",
  "Gnuplot": "gnuplot",
  "Go": "go",
  "Golo": "golo",
  "Gosu": "gosu",
  "Grace": "grace",
  "Gradle": "gradle",
  "Grammatical Framework": "grammatical-framework",
  "Graph Modeling Language": "graph-modeling language",
  "GraphQL": "graphql",
  "Graphviz (DOT)": "graphviz-(dot)",
  "Groovy": "groovy",
  "Groovy Server Pages": "groovy-server pages",
  "Hack": "hack",
  "Haml": "haml",
  "Handlebars": "handlebars",
  "HAProxy": "haproxy",
  "Harbour": "harbour",
  "Haskell": "haskell",
  "Haxe": "haxe",
  "HCL": "hcl",
  "HiveQL": "hiveql",
  "HLSL": "hlsl",
  "HolyC": "holyc",
  "HTML": "html",
  "HTML+Django": "html%2Bdjango",
  "HTML+ECR": "html%2Becr",
  "HTML+EEX": "html%2Beex",
  "HTML+ERB": "html%2Berb",
  "HTML+PHP": "html%2Bphp",
  "HTML+Razor": "html%2Brazor",
  "HTTP": "http",
  "HXML": "hxml",
  "Hy": "hy",
  "HyPhy": "hyphy",
  "IDL": "idl",
  "Idris": "idris",
  "Ignore List": "ignore-list",
  "IGOR Pro": "igor-pro",
  "Inform 7": "inform-7",
  "INI": "ini",
  "Inno Setup": "inno-setup",
  "Io": "io",
  "Ioke": "ioke",
  "IRC log": "irc-log",
  "Isabelle": "isabelle",
  "Isabelle ROOT": "isabelle-root",
  "J": "j",
  "Jasmin": "jasmin",
  "Java Properties": "java-properties",
  "Java Server Pages": "java-server pages",
  "JavaScript+ERB": "javascript%2Berb",
  "JFlex": "jflex",
  "Jison": "jison",
  "Jison Lex": "jison-lex",
  "Jolie": "jolie",
  "JSON": "json",
  "JSON with Comments": "json-with comments",
  "JSON5": "json5",
  "JSONiq": "jsoniq",
  "JSONLD": "jsonld",
  "Jsonnet": "jsonnet",
  "JSX": "jsx",
  "Julia": "julia",
  "Jupyter Notebook": "jupyter-notebook",
  "KiCad Layout": "kicad-layout",
  "KiCad Legacy Layout": "kicad-legacy layout",
  "KiCad Schematic": "kicad-schematic",
  "Kit": "kit",
  "KRL": "krl",
  "LabVIEW": "labview",
  "Lasso": "lasso",
  "Latte": "latte",
  "Lean": "lean",
  "Less": "less",
  "Lex": "lex",
  "LFE": "lfe",
  "LilyPond": "lilypond",
  "Limbo": "limbo",
  "Linker Script": "linker-script",
  "Linux Kernel Module": "linux-kernel module",
  "Liquid": "liquid",
  "Literate Agda": "literate-agda",
  "Literate CoffeeScript": "literate-coffeescript",
  "Literate Haskell": "literate-haskell",
  "LiveScript": "livescript",
  "LLVM": "llvm",
  "Logos": "logos",
  "Logtalk": "logtalk",
  "LOLCODE": "lolcode",
  "LookML": "lookml",
  "LoomScript": "loomscript",
  "LSL": "lsl",
  "LTspice Symbol": "ltspice-symbol",
  "Lua": "lua",
  "M": "m",
  "M4": "m4",
  "M4Sugar": "m4sugar",
  "Macaulay2": "macaulay2",
  "Makefile": "makefile",
  "Mako": "mako",
  "Markdown": "markdown",
  "Marko": "marko",
  "Mask": "mask",
  "Mathematica": "mathematica",
  "MATLAB": "matlab",
  "Maven POM": "maven-pom",
  "Max": "max",
  "MAXScript": "maxscript",
  "mcfunction": "mcfunction",
  "MediaWiki": "mediawiki",
  "Mercury": "mercury",
  "Meson": "meson",
  "Metal": "metal",
  "Microsoft Developer Studio Project": "microsoft-developer studio project",
  "MiniD": "minid",
  "Mirah": "mirah",
  "mIRC Script": "mirc-script",
  "MLIR": "mlir",
  "Modelica": "modelica",
  "Modula-2": "modula-2",
  "Modula-3": "modula-3",
  "Module Management System": "module-management system",
  "Monkey": "monkey",
  "Moocode": "moocode",
  "MoonScript": "moonscript",
  "Motorola 68K Assembly": "motorola-68k assembly",
  "MQL4": "mql4",
  "MQL5": "mql5",
  "MTML": "mtml",
  "MUF": "muf",
  "mupad": "mupad",
  "Muse": "muse",
  "Myghty": "myghty",
  "nanorc": "nanorc",
  "NASL": "nasl",
  "NCL": "ncl",
  "Nearley": "nearley",
  "Nemerle": "nemerle",
  "nesC": "nesc",
  "NetLinx": "netlinx",
  "NetLinx+ERB": "netlinx%2Berb",
  "NetLogo": "netlogo",
  "NewLisp": "newlisp",
  "Nextflow": "nextflow",
  "Nginx": "nginx",
  "Nim": "nim",
  "Ninja": "ninja",
  "Nit": "nit",
  "Nix": "nix",
  "NL": "nl",
  "NPM Config": "npm-config",
  "NSIS": "nsis",
  "Nu": "nu",
  "NumPy": "numpy",
  "ObjDump": "objdump",
  "Object Data Instance Notation": "object-data instance notation",
  "Objective-C": "objective-c",
  "Objective-C++": "objective-c%2B+",
  "Objective-J": "objective-j",
  "ObjectScript": "objectscript",
  "OCaml": "ocaml",
  "Odin": "odin",
  "Omgrofl": "omgrofl",
  "ooc": "ooc",
  "Opa": "opa",
  "Opal": "opal",
  "Open Policy Agent": "open-policy agent",
  "OpenCL": "opencl",
  "OpenEdge ABL": "openedge-abl",
  "OpenQASM": "openqasm",
  "OpenRC runscript": "openrc-runscript",
  "OpenSCAD": "openscad",
  "OpenStep Property List": "openstep-property list",
  "OpenType Feature File": "opentype-feature file",
  "Org": "org",
  "Ox": "ox",
  "Oxygene": "oxygene",
  "Oz": "oz",
  "P4": "p4",
  "Pan": "pan",
  "Papyrus": "papyrus",
  "Parrot": "parrot",
  "Parrot Assembly": "parrot-assembly",
  "Parrot Internal Representation": "parrot-internal representation",
  "Pascal": "pascal",
  "Pawn": "pawn",
  "Pep8": "pep8",
  "Perl": "perl",
  "PHP": "php",
  "Pic": "pic",
  "Pickle": "pickle",
  "PicoLisp": "picolisp",
  "PigLatin": "piglatin",
  "Pike": "pike",
  "PlantUML": "plantuml",
  "PLpgSQL": "plpgsql",
  "PLSQL": "plsql",
  "Pod": "pod",
  "Pod 6": "pod-6",
  "PogoScript": "pogoscript",
  "Pony": "pony",
  "PostCSS": "postcss",
  "PostScript": "postscript",
  "POV-Ray SDL": "pov-ray-sdl",
  "PowerBuilder": "powerbuilder",
  "PowerShell": "powershell",
  "Prisma": "prisma",
  "Processing": "processing",
  "Proguard": "proguard",
  "Prolog": "prolog",
  "Propeller Spin": "propeller-spin",
  "Protocol Buffer": "protocol-buffer",
  "Public Key": "public-key",
  "Pug": "pug",
  "Puppet": "puppet",
  "Pure Data": "pure-data",
  "PureBasic": "purebasic",
  "PureScript": "purescript",
  "Python console": "python-console",
  "Python traceback": "python-traceback",
  "q": "q",
  "QMake": "qmake",
  "QML": "qml",
  "Quake": "quake",
  "R": "r",
  "Racket": "racket",
  "Ragel": "ragel",
  "Raku": "raku",
  "RAML": "raml",
  "Rascal": "rascal",
  "Raw token data": "raw-token data",
  "RDoc": "rdoc",
  "Readline Config": "readline-config",
  "REALbasic": "realbasic",
  "Reason": "reason",
  "Rebol": "rebol",
  "Red": "red",
  "Redcode": "redcode",
  "Regular Expression": "regular-expression",
  "Ren'Py": "ren'py",
  "RenderScript": "renderscript",
  "reStructuredText": "restructuredtext",
  "REXX": "rexx",
  "RHTML": "rhtml",
  "Rich Text Format": "rich-text format",
  "Ring": "ring",
  "Riot": "riot",
  "RMarkdown": "rmarkdown",
  "RobotFramework": "robotframework",
  "Roff": "roff",
  "Roff Manpage": "roff-manpage",
  "Rouge": "rouge",
  "RPC": "rpc",
  "RPM Spec": "rpm-spec",
  "Ruby": "ruby",
  "RUNOFF": "runoff",
  "Rust": "rust",
  "Sage": "sage",
  "SaltStack": "saltstack",
  "SAS": "sas",
  "Sass": "sass",
  "Scala": "scala",
  "Scaml": "scaml",
  "Scheme": "scheme",
  "Scilab": "scilab",
  "SCSS": "scss",
  "sed": "sed",
  "Self": "self",
  "ShaderLab": "shaderlab",
  "Shell": "shell",
  "ShellSession": "shellsession",
  "Shen": "shen",
  "Sieve": "sieve",
  "Slash": "slash",
  "Slice": "slice",
  "Slim": "slim",
  "Smali": "smali",
  "Smalltalk": "smalltalk",
  "Smarty": "smarty",
  "SmPL": "smpl",
  "SMT": "smt",
  "Solidity": "solidity",
  "SourcePawn": "sourcepawn",
  "SPARQL": "sparql",
  "Spline Font Database": "spline-font database",
  "SQF": "sqf",
  "SQL": "sql",
  "SQLPL": "sqlpl",
  "Squirrel": "squirrel",
  "SRecode Template": "srecode-template",
  "SSH Config": "ssh-config",
  "Stan": "stan",
  "Standard ML": "standard-ml",
  "Starlark": "starlark",
  "Stata": "stata",
  "STON": "ston",
  "Stylus": "stylus",
  "SubRip Text": "subrip-text",
  "SugarSS": "sugarss",
  "SuperCollider": "supercollider",
  "Svelte": "svelte",
  "SVG": "svg",
  "Swift": "swift",
  "SWIG": "swig",
  "SystemVerilog": "systemverilog",
  "Tcl": "tcl",
  "Tcsh": "tcsh",
  "Tea": "tea",
  "Terra": "terra",
  "TeX": "tex",
  "Texinfo": "texinfo",
  "Text": "text",
  "Textile": "textile",
  "Thrift": "thrift",
  "TI Program": "ti-program",
  "TLA": "tla",
  "TOML": "toml",
  "TSQL": "tsql",
  "TSX": "tsx",
  "Turing": "turing",
  "Turtle": "turtle",
  "Twig": "twig",
  "TXL": "txl",
  "Type Language": "type-language",
  "Unified Parallel C": "unified-parallel c",
  "Unity3D Asset": "unity3d-asset",
  "Unix Assembly": "unix-assembly",
  "Uno": "uno",
  "UnrealScript": "unrealscript",
  "UrWeb": "urweb",
  "V": "v",
  "Vala": "vala",
  "VBA": "vba",
  "VBScript": "vbscript",
  "VCL": "vcl",
  "Verilog": "verilog",
  "VHDL": "vhdl",
  "Vim script": "vim-script",
  "Vim Snippet": "vim-snippet",
  "Visual Basic .NET": "visual-basic .net",
  "Volt": "volt",
  "Vue": "vue",
  "Wavefront Material": "wavefront-material",
  "Wavefront Object": "wavefront-object",
  "wdl": "wdl",
  "Web Ontology Language": "web-ontology language",
  "WebAssembly": "webassembly",
  "WebIDL": "webidl",
  "WebVTT": "webvtt",
  "Wget Config": "wget-config",
  "Windows Registry Entries": "windows-registry entries",
  "wisp": "wisp",
  "Wollok": "wollok",
  "World of Warcraft Addon Data": "world-of warcraft addon data",
  "X BitMap": "x-bitmap",
  "X Font Directory Index": "x-font directory index",
  "X PixMap": "x-pixmap",
  "X10": "x10",
  "xBase": "xbase",
  "XC": "xc",
  "XCompose": "xcompose",
  "XML": "xml",
  "XML Property List": "xml-property list",
  "Xojo": "xojo",
  "XPages": "xpages",
  "XProc": "xproc",
  "XQuery": "xquery",
  "XS": "xs",
  "XSLT": "xslt",
  "Xtend": "xtend",
  "Yacc": "yacc",
  "YAML": "yaml",
  "YANG": "yang",
  "YARA": "yara",
  "YASnippet": "yasnippet",
  "ZAP": "zap",
  "ZenScript": "zenscript",
  "Zephir": "zephir",
  "Zig": "zig",
  "ZIL": "zil",
  "Zimpl": "zimpl"
};
