export enum StroageKey {
  REPO_SINCE = 'REPO_SINCE',
  REPO_LANGUAGE = 'REPO_LANGUAGE',
  REPO_SPOKEN_LANGUAGE = 'REPO_SPOKEN_LANGUAGE',
  USER_SINCE = 'USER_SINCE',
  USER_LANGUAGE = 'USER_LANGUAGE',
  LIKE = 'LIKE',
}
